#!/bin/bash

# =============================================================================
# SSH DEĞİŞKENLERİ
# =============================================================================
readonly SSH_BAK_FILE="/etc/ssh/sshd_config.backup.$(date +%Y%m%d_%H%M%S)"
readonly SSH_CUSTOM_CONF="/etc/ssh/sshd_config.d/99-hardening.conf"

# =============================================================================
# SSH FONKSİYONLARI
# =============================================================================

# SSH port ayarı
configure_ssh_port() {
    print_message "\n🚪 SSH PORT AYARI" "$CYAN"
    print_message "─────────────────" "$BLUE"

    CURRENT_PORT=$(sudo grep -E "^Port\s+" /etc/ssh/sshd_config 2>/dev/null | awk '{print $2}' || echo "22")
    print_message "Mevcut SSH Port: $CURRENT_PORT" "$YELLOW"

    while true; do
        read -p "Yeni SSH portu (22 veya 1024-65535, varsayılan: $CURRENT_PORT): " SSH_PORT
        SSH_PORT=${SSH_PORT:-$CURRENT_PORT}

        if [[ "$SSH_PORT" =~ ^[0-9]+$ ]] && [ "$SSH_PORT" -ge 22 ] && [ "$SSH_PORT" -le 65535 ]; then
            if [ "$SSH_PORT" -eq 22 ]; then
                print_message "ℹ️  Port 22 (varsayılan SSH portu) kullanılacak." "$YELLOW"
                print_message "⚠️  Daha yüksek güvenlik için 1024-65535 arası bir port önerilir." "$RED"
                read -p "22 portunu kullanmak istediğinizden emin misiniz? (e/h): " confirm_port
                if [[ ! $confirm_port =~ ^[Ee]([Ee]vet)?$ ]]; then
                    continue
                fi
            elif [ "$SSH_PORT" -lt 1024 ] && [ "$SSH_PORT" -ne 22 ]; then
                print_message "⚠️  Port $SSH_PORT (1024'ten küçük) seçtiniz. Bu portlar sistem portlarıdır." "$YELLOW"
                read -p "Port $SSH_PORT kullanmak istediğinizden emin misiniz? (e/h): " confirm_port
                if [[ ! $confirm_port =~ ^[Ee]([Ee]vet)?$ ]]; then
                    continue
                fi
            fi
            break
        else
            print_message "❌ Geçersiz port! 22 veya 1024-65535 arasında olmalı." "$RED"
        fi
    done

    print_message "✅ SSH portu $SSH_PORT olarak ayarlandı" "$GREEN"
    log_message "SSH portu $SSH_PORT olarak ayarlandı"
}

# SSH yapılandırması
configure_ssh() {
    print_message "\n🔧 SSH KONFİGÜRASYONU" "$CYAN"
    print_message "──────────────────────" "$BLUE"

    # SSH config dizinini oluştur
    sudo mkdir -p /etc/ssh/sshd_config.d

    # Mevcut config'i yedekle
    if [[ -f /etc/ssh/sshd_config ]]; then
        sudo cp /etc/ssh/sshd_config "$SSH_BAK_FILE"
        print_message "📋 SSH config yedeklendi: $SSH_BAK_FILE" "$GREEN"
    fi

    # Kimlik doğrulama yöntemi seçimi
    print_message "\n🔐 KİMLİK DOĞRULAMA YÖNTEMİ" "$BLUE"
    echo ""
    echo "1) 🔓 Parola ile giriş (önerilmez, güvenlik: ⭐)"
    echo "2) 🔐 Parola + 2FA ile giriş (önemli, güvenlik: ⭐⭐)"
    echo "3) 🔑 SSH Anahtarı ile giriş (önerilir, güvenlik: ⭐⭐⭐⭐)"
    echo "4) 🛡️  SSH Anahtarı + 2FA ile giriş (tavsiye edilen, güvenlik: ⭐⭐⭐⭐⭐)"
    echo ""

    while true; do
        read -p "Seçiminiz (1/2/3/4): " AUTH_CHOICE
        
        # Bu değişkeni global olarak kullanacağız (module scope)
        # Diğer fonksiyonlardan erişilebilmesi için export ediyoruz veya global varsayıyoruz.
        # En iyisi çağırıldığı yerde source edildiği için global kalır.
        
        case $AUTH_CHOICE in
            1)
                AUTH_METHOD="Parola"
                SECURITY_LEVEL="⭐"
                PASSWORD_AUTH="yes"
                PUBKEY_AUTH="no"
                ;;
            2)
                AUTH_METHOD="Parola + 2FA"
                SECURITY_LEVEL="⭐⭐"
                PASSWORD_AUTH="yes"
                PUBKEY_AUTH="no"
                ;;
            3)
                AUTH_METHOD="SSH Anahtarı"
                SECURITY_LEVEL="⭐⭐⭐⭐"
                PASSWORD_AUTH="no"
                PUBKEY_AUTH="yes"
                ;;
            4)
                AUTH_METHOD="SSH Anahtarı + 2FA"
                SECURITY_LEVEL="⭐⭐⭐⭐⭐"
                PASSWORD_AUTH="no"  # 4. seçenekte PAROLA KAPALI
                PUBKEY_AUTH="yes"
                ;;
            *)
                print_message "❌ Geçersiz seçim!" "$RED"
                continue
                ;;
        esac
        break
    done

    print_message "\n✅ Seçilen yöntem: $AUTH_METHOD ($SECURITY_LEVEL)" "$GREEN"

    # Özel SSH config dosyasını oluştur
    sudo tee "$SSH_CUSTOM_CONF" > /dev/null << EOF
# SSH Hardening Configuration
# Generated on $(date)
# DO NOT EDIT THIS FILE MANUALLY

Port $SSH_PORT
Protocol 2
PermitRootLogin no
MaxAuthTries 3
MaxSessions 3
ClientAliveInterval 300
ClientAliveCountMax 2
LoginGraceTime 120
StrictModes yes
X11Forwarding no
PrintMotd no
PrintLastLog yes
TCPKeepAlive yes
UsePAM yes
UseDNS no
Compression no
AllowGroups sshusers
PasswordAuthentication $PASSWORD_AUTH
PubkeyAuthentication $PUBKEY_AUTH
ChallengeResponseAuthentication yes
EOF

    # AuthenticationMethods ayarı
    case $AUTH_CHOICE in
        1)
            # Sadece parola
            echo "AuthenticationMethods password" | sudo tee -a "$SSH_CUSTOM_CONF" > /dev/null
            ;;
        2)
            # Parola + 2FA (önce parola, sonra 2FA)
            echo "AuthenticationMethods password,keyboard-interactive" | sudo tee -a "$SSH_CUSTOM_CONF" > /dev/null
            ;;
        3)
            # Sadece SSH anahtarı
            echo "AuthenticationMethods publickey" | sudo tee -a "$SSH_CUSTOM_CONF" > /dev/null
            ;;
        4)
            # SSH anahtarı + 2FA (önce SSH anahtarı, sonra 2FA) - PAROLA YOK!
            echo "AuthenticationMethods publickey,keyboard-interactive" | sudo tee -a "$SSH_CUSTOM_CONF" > /dev/null
            ;;
    esac

    # SSH servisi için gerekli dizinleri oluştur
    print_message "\n🔧 SSH servisi için gerekli dizinler oluşturuluyor..." "$YELLOW"
    sudo mkdir -p /run/sshd
    sudo chmod 0755 /run/sshd

    # SSH host key'lerini oluştur (eğer yoksa)
    if [[ ! -f /etc/ssh/ssh_host_ed25519_key ]]; then
        sudo ssh-keygen -A >/dev/null 2>&1 || true
    fi

    # SSH config testi
    print_message "🔍 SSH config test ediliyor..." "$YELLOW"
    if sudo sshd -t 2>&1; then
        print_message "✅ SSH config testi başarılı" "$GREEN"
    else
        print_message "⚠️  SSH config testinde uyarı, düzeltiliyor..." "$YELLOW"
        # Hata mesajını göster
        sudo sshd -t 2>&1 | grep -v "Warning" || true

        # Hata durumunda manuel düzeltme yap
        sudo sed -i '/^Include/d' /etc/ssh/sshd_config
        echo "Include /etc/ssh/sshd_config.d/*.conf" | sudo tee -a /etc/ssh/sshd_config > /dev/null

        # Tekrar test et
        if sudo sshd -t 2>&1; then
            print_message "✅ SSH config düzeltildi ve test edildi" "$GREEN"
        else
            print_message "⚠️  SSH config testinde hata, ancak devam ediliyor..." "$RED"
        fi
    fi
}

# SSH anahtar yönetimi
manage_ssh_keys() {
    if [[ "$AUTH_CHOICE" == "3" || "$AUTH_CHOICE" == "4" ]]; then
        print_message "\n🔑 SSH ANAHTAR YÖNETİMİ" "$CYAN"
        print_message "───────────────────────" "$BLUE"

        # Sunucu hostname'ini al
        SERVER_HOSTNAME=$(hostname | cut -d'.' -f1 | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9]//g')
        if [ -z "$SERVER_HOSTNAME" ]; then
            SERVER_HOSTNAME="server"
        fi

        KEY_NAME="$SERVER_HOSTNAME"
        IP_ADDRESS=$(hostname -I | awk '{print $1}')

        print_message "\n📋 İSTEMCİ TARAFINDA YAPILACAKLAR:" "$YELLOW"
        print_message "──────────────────────────────────" "$BLUE"
        echo ""
        print_message "1. SSH anahtar çifti oluşturun:" "$GREEN"
        print_message "   ssh-keygen -t ed25519 -f ~/.ssh/$KEY_NAME" "$CYAN"
        print_message "   (Parola kısmını boş bırakabilirsiniz - sadece Enter'a basın)" "$YELLOW"
        echo ""
        print_message "2. Private key izinlerini ayarlayın:" "$GREEN"
        print_message "   chmod 600 ~/.ssh/$KEY_NAME" "$CYAN"
        echo ""
        print_message "3. Public key içeriğini görüntüleyin:" "$GREEN"
        print_message "   cat ~/.ssh/$KEY_NAME.pub" "$CYAN"
        echo ""
        print_message "4. Aşağıdaki satıra public key içeriğini KOPYALAYIP YAPIŞTIRIN:" "$RED"
        print_message "(Tüm satırı kopyalayın, ENTER + Ctrl+D ile bitirin)" "$BLUE"
        print_message "Örnek format: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAI..." "$YELLOW"
        echo ""
        print_message "⚠️  DİKKAT: Public key'i doğru kopyaladığınızdan emin olun!" "$RED"
        echo "════════════════════════════════════════════════════════════════════════════════"
        echo ""

        # Public key alma döngüsü - DOĞRU KEY GİRİLENE KADAR DEVAM ET
        while true; do
            print_message "📋 PUBLIC KEY İÇERİĞİNİ YAPIŞTIRIN (ENTER + Ctrl+D ile bitirin):" "$GREEN"
            print_message "─────────────────────────────────────────────────────────" "$BLUE"

            # Public key'i oku (birden fazla satır olabilir)
            PUBLIC_KEY=""
            while IFS= read -r line; do
                if [[ -n "$line" ]]; then
                    PUBLIC_KEY+="$line"$'\n'
                fi
            done

            # Trim whitespace (baştaki ve sondaki boşlukları temizle)
            PUBLIC_KEY=$(echo "$PUBLIC_KEY" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')

            # SSH key formatını kontrol et
            if [[ -n "$PUBLIC_KEY" ]] && [[ "$PUBLIC_KEY" =~ ^(ssh-(ed25519|rsa|dss|ecdsa)|ecdsa-sha2-nistp(256|384|521)|sk-(ssh-ed25519|ecdsa-sha2-nistp256)) ]]; then
                print_message "\n✅ PUBLIC KEY FORMATI DOĞRU" "$GREEN"
                print_message "Key tipi: $(echo "$PUBLIC_KEY" | awk '{print $1}')" "$CYAN"

                # .ssh dizinini oluştur
                sudo -u "$NEW_USER" mkdir -p "/home/$NEW_USER/.ssh" 2>/dev/null || true

                # authorized_keys dosyasına ekle (append)
                echo "$PUBLIC_KEY" | sudo -u "$NEW_USER" tee -a "/home/$NEW_USER/.ssh/authorized_keys" > /dev/null

                # İzinleri ayarla
                sudo chmod 700 "/home/$NEW_USER/.ssh" 2>/dev/null || true
                sudo chmod 600 "/home/$NEW_USER/.ssh/authorized_keys" 2>/dev/null || true
                sudo chown -R "$NEW_USER:$NEW_USER" "/home/$NEW_USER/.ssh" 2>/dev/null || true

                # Key parmak izini al
                KEY_FINGERPRINT=$(echo "$PUBLIC_KEY" | ssh-keygen -lf - 2>/dev/null | awk '{print $2}' || echo "Bilinmiyor")

                print_message "\n✅ PUBLIC KEY BAŞARIYLA KAYDEDİLDİ" "$GREEN"
                print_message "• Dosya: /home/$NEW_USER/.ssh/authorized_keys" "$CYAN"
                print_message "• Key parmak izi: $KEY_FINGERPRINT" "$CYAN"

                log_message "Public key eklendi: $(echo "$PUBLIC_KEY" | awk '{print $1}') - $KEY_FINGERPRINT"
                break  # Başarılı, döngüden çık

            else
                print_message "\n❌ GEÇERSİZ PUBLIC KEY FORMATI!" "$RED"
                print_message "Lütfen aşağıdaki formatlardan birini kullandığınızdan emin olun:" "$YELLOW"
                print_message "• ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAI..." "$GREEN"
                print_message "• ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC..." "$GREEN"
                print_message "• ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAI..." "$GREEN"
                print_message "" "$NC"

                if [[ -n "$PUBLIC_KEY" ]]; then
                    print_message "Girdiğiniz key (ilk 50 karakter):" "$BLUE"
                    echo "\"${PUBLIC_KEY:0:50}...\""
                else
                    print_message "Girdiğiniz key BOŞ!" "$RED"
                fi

                print_message "" "$NC"
                print_message "Lütfen tekrar deneyin..." "$YELLOW"
                echo ""
            fi
        done

        # Bağlantı testi için komut göster
        print_message "\n🔗 BAĞLANTI TESTİ:" "$CYAN"
        print_message "─────────────────" "$BLUE"
        print_message "SSH anahtarınızla bağlantıyı test edin:" "$GREEN"
        print_message "ssh -p $SSH_PORT -i ~/.ssh/$KEY_NAME $NEW_USER@$IP_ADDRESS" "$YELLOW"

        if check_internet; then
            PUBLIC_IP=$(curl -s --connect-timeout 3 icanhazip.com 2>/dev/null || echo "")
            if [[ -n "$PUBLIC_IP" ]]; then
                print_message "veya:" "$BLUE"
                print_message "ssh -p $SSH_PORT -i ~/.ssh/$KEY_NAME $NEW_USER@$PUBLIC_IP" "$YELLOW"
            fi
        fi

        # 2FA ile birlikte kullanılacaksa ek bilgi
        if [[ "$AUTH_CHOICE" == "4" ]]; then
            print_message "\n📱 2FA NOTU:" "$CYAN"
            print_message "Bağlantı sırasında SSH anahtarınızdan sonra Google Authenticator kodu istenecektir." "$YELLOW"
        fi
    fi
}

# SSH servisini yeniden başlat
restart_ssh_service() {
    print_message "\n🔄 SSH SERVİSİ YENİDEN BAŞLATILIYOR" "$CYAN"
    print_message "─────────────────────────────────" "$BLUE"

    sudo systemctl restart ssh >> "$LOG_FILE" 2>&1
    sudo systemctl enable ssh >> "$LOG_FILE" 2>&1

    print_message "✅ SSH servisi yeniden başlatıldı" "$GREEN"
}
